import Link from "next/link";
import Header from "@/components/Header";
import { ArrowRight, Sparkles, Target, TrendingUp } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen">
      <Header />
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto text-center space-y-8">
          <h1 className="text-5xl md:text-6xl font-bold text-foreground">
            Your Personal
            <span className="text-primary"> Fitness Coach</span>
          </h1>
          <p className="text-xl text-warm-gray max-w-2xl mx-auto">
            AI-powered workout plans tailored to your goals. Achieve the body you want with
            personalized guidance and daily motivation.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/api/auth/login"
              className="px-8 py-4 rounded-lg bg-primary text-white hover:bg-primary-dark transition-colors text-lg font-medium flex items-center justify-center gap-2"
            >
              Get Started
              <ArrowRight className="w-5 h-5" />
            </Link>
            <Link
              href="/dashboard"
              className="px-8 py-4 rounded-lg bg-muted text-foreground hover:bg-accent transition-colors text-lg font-medium"
            >
              Learn More
            </Link>
          </div>
        </div>

        <div className="mt-24 grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          <div className="bg-card rounded-xl p-6 shadow-sm border border-border">
            <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mb-4">
              <Sparkles className="w-6 h-6 text-primary" />
            </div>
            <h3 className="text-xl font-semibold text-foreground mb-2">AI-Powered Plans</h3>
            <p className="text-warm-gray">
              Get personalized workout schedules generated by AI based on your body type goals and
              fitness level.
            </p>
          </div>

          <div className="bg-card rounded-xl p-6 shadow-sm border border-border">
            <div className="w-12 h-12 rounded-full bg-secondary/10 flex items-center justify-center mb-4">
              <Target className="w-6 h-6 text-secondary" />
            </div>
            <h3 className="text-xl font-semibold text-foreground mb-2">Daily Motivation</h3>
            <p className="text-warm-gray">
              Check in daily to track your mood and motivation. Build streaks and stay accountable
              to your fitness journey.
            </p>
          </div>

          <div className="bg-card rounded-xl p-6 shadow-sm border border-border">
            <div className="w-12 h-12 rounded-full bg-accent/50 flex items-center justify-center mb-4">
              <TrendingUp className="w-6 h-6 text-warm-gray" />
            </div>
            <h3 className="text-xl font-semibold text-foreground mb-2">Progress Tracking</h3>
            <p className="text-warm-gray">
              Monitor your progress with weight tracking, measurements, and visual charts to see
              your transformation.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
